name: Release

on:
  pull_request:
  push:
    branches: master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
          
          
      - run: pnpm install
      - run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - uses: ethomson/send-tweet-action@ee76e315ba1f8fed3444282c3c8be0fbb369c751
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && env.SEMVER_VERSION != '' }}
        with:
          status: "${{github.repository}} V${{ env.SEMVER_VERSION }} is published!\n\nhttps://www.npmjs.com/package/electron-google-oauth2\n\n@github #send_tweet_action @npmjs @electronjs\n\nAvailable in Github"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
